---
type: docker
kind: pipeline
name: build-dev

steps:

  - name: run-tests
    image: harbor.swokiz.dev/hub-proxy/library/python:3.11-bookworm
    depends_on: [ clone ]
    environment:
      PLUGIN_CONFIG:
        from_secret: image-swokiz-dev-json
    commands:
      - python3 -m pip install -r requirements.txt
      - python3 test.py

  - name: kaninko-build-dev
    image: harbor.swokiz.dev/hub-proxy/plugins/kaniko
    depends_on: [ clone ]
    environment:
      PLUGIN_CONFIG:
        from_secret: image-swokiz-dev-json
    settings:
      repo: "harbor.swokiz.dev/swokiz/tool-python-pdf-merger"
      registry: harbor.swokiz.dev
      dockerfile: Dockerfile
      tags:
        - dev

image_pull_secrets:
  - image-swokiz-dev-json

---

type: docker
kind: pipeline
name: on-tagged-commit

steps:

  - name: kaninko-build-prod
    image: harbor.swokiz.dev/hub-proxy/plugins/kaniko
    depends_on: [ clone ]
    environment:
      PLUGIN_CONFIG:
        from_secret: image-swokiz-dev-json
    settings:
      repo: "harbor.swokiz.dev/swokiz/tool-python-pdf-merger"
      registry: harbor.swokiz.dev
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}
        - latest

image_pull_secrets:
  - image-swokiz-dev-json

trigger:
  event:
  - tag
